### ISSUE TITLE
能否运用在SegFormer上

### ISSUE THREAD

**Issue by hhuzzz** [nizhenliang/CGRSeg#3]
能否将CGRSeg与SegFormer的backbone MiT结合，因为我看您使用的是EfficientFormer。请问您是否有过相关尝试呢？
ps:之前试过SSA（您的另一篇文章），但是我的数据集上效果不佳

**Comment by nizhenliang** [comment]
可以的，可以在mmseg配置文件中直接替换backbone的部分。

**Comment by nizhenliang** [comment]
SSA中您是用的segformer吗？精度差了多少呢？可以在SSA那个库issue下咱们详细讨论一下。

**Comment by hhuzzz** [comment]
> 可以的，可以在mmseg配置文件中直接替换backbone的部分。

您好，在rcm.py中，这些包并没有在仓库中提供，我在mmsegmentation库中似乎也没有看到
```
from ..layers import DropPath
from ..layers.helpers import to_2tuple
```

**Comment by ZhenboZhao77** [comment]
from ..layers import DropPath
from ..layers.helpers import to_2tuple
换成这样即可：
from timm.layers import DropPath
from timm.layers.helpers import to_2tuple
